// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9VnW1vNwsqdwwrnNOc9sJ7x2gUYDyjRc',
    appId: '1:266312093802:web:68eb3d124854009a423a13',
    messagingSenderId: '266312093802',
    projectId: 'expense-tracker-cc8af',
    authDomain: 'expense-tracker-cc8af.firebaseapp.com',
    storageBucket: 'expense-tracker-cc8af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADuEzdfsG2g9dRxOo8xMDUZz7Sms3qtE0',
    appId: '1:266312093802:android:9fb51a940656ab63423a13',
    messagingSenderId: '266312093802',
    projectId: 'expense-tracker-cc8af',
    storageBucket: 'expense-tracker-cc8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPdze4SbPrATFopZgEUfD5T1u-vU8UkLk',
    appId: '1:266312093802:ios:235c1f7052e3399f423a13',
    messagingSenderId: '266312093802',
    projectId: 'expense-tracker-cc8af',
    storageBucket: 'expense-tracker-cc8af.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPdze4SbPrATFopZgEUfD5T1u-vU8UkLk',
    appId: '1:266312093802:ios:235c1f7052e3399f423a13',
    messagingSenderId: '266312093802',
    projectId: 'expense-tracker-cc8af',
    storageBucket: 'expense-tracker-cc8af.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9VnW1vNwsqdwwrnNOc9sJ7x2gUYDyjRc',
    appId: '1:266312093802:web:62c9548dd9a8d014423a13',
    messagingSenderId: '266312093802',
    projectId: 'expense-tracker-cc8af',
    authDomain: 'expense-tracker-cc8af.firebaseapp.com',
    storageBucket: 'expense-tracker-cc8af.firebasestorage.app',
  );
}
